reformat source code
removed tabs and set indention to 4 spaces
added emacs and vi format headers

diff --git a/dracut b/dracut
--- a/dracut
+++ b/dracut
@@ -1,11 +1,13 @@
 #!/bin/bash
+# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
+# ex: ts=8 sw=4 sts=4 et filetype=sh
 # 
 # Generator script for a dracut initramfs
 # Tries to retain some degree of compatibility with the command line
 # of the various mkinitrd implementations out there
 #
 
-# Copyright 2005-2009 Red Hat, Inc.  All rights reserved.
+# Copyright 2005-2010 Red Hat, Inc.  All rights reserved.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,7 +26,8 @@
 
 usage() {
 #                                                       80x25 linebreak here ^
-	echo "Usage: $0 [OPTION]... <initramfs> <kernel-version>
+    cat << EOF
+Usage: $0 [OPTION]... <initramfs> <kernel-version>
 Creates initial ramdisk images for preloading modules
 
   -f, --force           Overwrite existing initramfs file.
@@ -48,21 +51,21 @@ Creates initial ramdisk images for preloading modules
   --no-kernel           Do not install kernel drivers and firmware files
   --ignore-kernel-modules
                         Don't try to load modules. It automatically implies
-                        '--no-kernel'. It's assumed that everything needed
-                        is built into kernel.
+                         '--no-kernel'. It's assumed that everything needed
+                         is built into kernel.
   --strip               Strip binaries in the initramfs
   --nostrip             Do not strip binaries in the initramfs (default)
   --mdadmconf           Include local /etc/mdadm.conf
   --nomdadmconf         Do not include local /etc/mdadm.conf
   --lvmconf             Include local /etc/lvm/lvm.conf
-  --nolvmconf             Do not include local /etc/lvm/lvm.conf
+  --nolvmconf           Do not include local /etc/lvm/lvm.conf
   -h, --help            This message
   --debug               Output debug information of the build process
   -v, --verbose         Verbose output during the build process
   -c, --conf [FILE]     Specify configuration file to use.
                          Default: /etc/dracut.conf
-  --confdir [DIR]       Specify configuration directory to use *.conf files from.
-                         Default: /etc/dracut.conf.d
+  --confdir [DIR]       Specify configuration directory to use *.conf files 
+                         from. Default: /etc/dracut.conf.d
   -l, --local           Local mode. Use modules from the current working
                          directory instead of the system-wide installed in
                          /usr/share/dracut/modules.d.
@@ -76,17 +79,17 @@ Creates initial ramdisk images for preloading modules
   -I, --install [LIST]  Install the space separated list of files into the
                          initramfs.
   --gzip                Compress the generated initramfs using gzip.
-                        This will be done by default, unless another
-                        compression option or --no-compress is passed.
+                         This will be done by default, unless another
+                         compression option or --no-compress is passed.
   --bzip2               Compress the generated initramfs using bzip2.
-                        Make sure your kernel has bzip2 decompression support
-                        compiled in, otherwise you will not be able to boot.
-  --lzma                  Compress the generated initramfs using lzma.
-                        Make sure your kernel has lzma support compiled in, 
-                        otherwise you will not be able to boot.
+                         Make sure your kernel has bzip2 decompression support
+                         compiled in, otherwise you will not be able to boot.
+  --lzma                Compress the generated initramfs using lzma.
+                         Make sure your kernel has lzma support compiled in, 
+                         otherwise you will not be able to boot.
   --no-compress         Do not compress the generated initramfs.  This will
-                        override any other compression options.
-"
+                         override any other compression options.
+EOF
 }
 
 # Little helper function for reading args from the commandline.
@@ -98,44 +101,44 @@ read_arg() {
     # $3 = arg parameter
     local rematch='^[^=]*=(.*)$'
     if [[ $2 =~ $rematch ]]; then
-	read "$1" <<< "${BASH_REMATCH[1]}"
+        read "$1" <<< "${BASH_REMATCH[1]}"
     else
-	read "$1" <<< "$3"
-	# There is no way to shift our callers args, so
-	# return 1 to indicate they should do it instead.
-	return 1
+        read "$1" <<< "$3"
+        # There is no way to shift our callers args, so
+        # return 1 to indicate they should do it instead.
+        return 1
     fi
 }
 
 while (($# > 0)); do
     case ${1%%=*} in
-	-m|--modules)  read_arg dracutmodules_l      "$@" || shift;;
-	-o|--omit)     read_arg omit_dracutmodules_l "$@" || shift;;
-	-a|--add)      read_arg add_dracutmodules_l  "$@" || shift;;
-	-d|--drivers)  read_arg drivers_l            "$@" || shift;;
-	--add-drivers) read_arg add_drivers_l        "$@" || shift;;
-	--filesystems) read_arg filesystems_l        "$@" || shift;;
-	-k|--kmoddir)  read_arg drivers_dir_l        "$@" || shift;;
-	-c|--conf)     read_arg conffile             "$@" || shift;;
-	--confdir)     read_arg confdir              "$@" || shift;;
-	-I|--install)  read_arg install_items        "$@" || shift;;
-	--fwdir)       read_arg fw_dir_l             "$@" || shift;;
-	-f|--force)    force=yes;;
-	--kernel-only) kernel_only="yes"; no_kernel="no";;
-	--no-kernel)   kernel_only="no"; no_kernel="yes";;
-	--strip)       do_strip_l="yes";;
-	--nostrip)     do_strip_l="no";;
+        -m|--modules)  read_arg dracutmodules_l      "$@" || shift;;
+        -o|--omit)     read_arg omit_dracutmodules_l "$@" || shift;;
+        -a|--add)      read_arg add_dracutmodules_l  "$@" || shift;;
+        -d|--drivers)  read_arg drivers_l            "$@" || shift;;
+        --add-drivers) read_arg add_drivers_l        "$@" || shift;;
+        --filesystems) read_arg filesystems_l        "$@" || shift;;
+        -k|--kmoddir)  read_arg drivers_dir_l        "$@" || shift;;
+        -c|--conf)     read_arg conffile             "$@" || shift;;
+        --confdir)     read_arg confdir              "$@" || shift;;
+        -I|--install)  read_arg install_items        "$@" || shift;;
+        --fwdir)       read_arg fw_dir_l             "$@" || shift;;
+        -f|--force)    force=yes;;
+        --kernel-only) kernel_only="yes"; no_kernel="no";;
+        --no-kernel)   kernel_only="no"; no_kernel="yes";;
+        --strip)       do_strip_l="yes";;
+        --nostrip)     do_strip_l="no";;
         --mdadmconf)   mdadmconf_l="yes";;
         --nomdadmconf) mdadmconf_l="no";;
         --lvmconf)     lvmconf_l="yes";;
         --nolvmconf)   lvmconf_l="no";;
-	--debug)       debug="yes";;
-	-v|--verbose)  beverbose="yes";;
-	-l|--local)    allowlocal="yes" ;;
-	-H|--hostonly) hostonly_l="yes" ;;
-	--fstab)       use_fstab_l="yes" ;;
-	-h|--help)     usage; exit 1 ;;
-	-i|--include)  include_src="$2"; include_target="$3"; shift 2;;
+        --debug)       debug="yes";;
+        -v|--verbose)  beverbose="yes";;
+        -l|--local)    allowlocal="yes" ;;
+        -H|--hostonly) hostonly_l="yes" ;;
+        --fstab)       use_fstab_l="yes" ;;
+        -h|--help)     usage; exit 1 ;;
+        -i|--include)  include_src="$2"; include_target="$3"; shift 2;;
         --bzip2)       [[ $compress != cat ]] && compress="bzip2 -9";;
         --lzma)          [[ $compress != cat ]] && compress="lzma -9";;
         --no-compress) compress="cat";;
@@ -147,8 +150,8 @@ while (($# > 0)); do
             ignore_kmodules="yes"
             omit_dracutmodules_l+=\ kernel-modules
             ;;
-	-*) printf "\nUnknown option: %s\n\n" "$1" >&2; usage; exit 1;;
-	*) break ;;
+        -*) printf "\nUnknown option: %s\n\n" "$1" >&2; usage; exit 1;;
+        *) break ;;
     esac
     shift
 done
@@ -163,7 +166,8 @@ export PATH
 
 [[ $dracutbasedir ]] || dracutbasedir=/usr/share/dracut
 
-[[ $allowlocal && -f "$(readlink -f ${0%/*})/dracut-functions" ]] && dracutbasedir="${0%/*}" 
+[[ $allowlocal && -f "$(readlink -f ${0%/*})/dracut-functions" ]] && \
+    dracutbasedir="${0%/*}" 
 
 # if we were not passed a config file, try the default one
 if [[ ! -f $conffile ]]; then
@@ -182,7 +186,7 @@ fi
 # source our config dir
 if [[ $confdir && -d $confdir ]]; then
     for f in "$confdir"/*.conf; do 
-	[[ -e $f ]] && . "$f"
+        [[ -e $f ]] && . "$f"
     done
 fi
 
@@ -213,11 +217,12 @@ fw_dir=${fw_dir//:/ }
 [[ $compress ]] || compress="gzip -9"
 
 if [[ -f $dracutbasedir/dracut-functions ]]; then
-   . $dracutbasedir/dracut-functions
+    . $dracutbasedir/dracut-functions
 else
-   echo "Cannot find $dracutbasedir/dracut-functions. Are you running from a git checkout?"
-   echo "Try passing -l as an argument to $0"
-   exit 1
+    echo "Cannot find $dracutbasedir/dracut-functions."
+    echo "Are you running from a git checkout?"
+    echo "Try passing -l as an argument to $0"
+    exit 1
 fi
 
 dracutfunctions=$dracutbasedir/dracut-functions
@@ -270,13 +275,16 @@ elif [[ -f "$outfile" && ! -w "$outfile" ]]; then
     exit 1
 fi
 
-hookdirs="cmdline pre-udev pre-trigger netroot pre-mount pre-pivot mount emergency"
+hookdirs="cmdline pre-udev pre-trigger netroot pre-mount"
+hookdirs+=" pre-pivot mount emergency"
 
 [[ $TMPDIR && ! -w $TMPDIR ]] && unset TMPDIR
 readonly initdir=$(mktemp -d -t initramfs.XXXXXX)
 
-trap 'ret=$?;rm -rf "$initdir";exit $ret;' EXIT # clean up after ourselves no matter how we die.
-trap 'exit 1;' SIGINT # clean up after ourselves no matter how we die.
+# clean up after ourselves no matter how we die.
+trap 'ret=$?;rm -rf "$initdir";exit $ret;' EXIT 
+# clean up after ourselves no matter how we die.
+trap 'exit 1;' SIGINT 
 
 # Need to be able to have non-root users read stuff (rpcbind etc)
 chmod 755 "$initdir"
@@ -288,29 +296,30 @@ export initdir hookdirs dracutbasedir dracutmodules drivers \
 
 if [[ $kernel_only != yes ]]; then
     # Create some directory structure first
-    for d in bin sbin usr/bin usr/sbin usr/lib etc proc sys sysroot tmp dev/pts var/run; do 
-	inst_dir "/$d"; 
+    for d in bin sbin usr/bin usr/sbin usr/lib etc \
+        proc sys sysroot tmp dev/pts var/run; do 
+        inst_dir "/$d"; 
     done
 fi
 
 # check all our modules to see if they should be sourced.
 # This builds a list of modules that we will install next.
 check_modules
-  
+
 # source our modules.
 for moddir in "$dracutbasedir/modules.d"/[0-9][0-9]*; do
     mod=${moddir##*/}; mod=${mod#[0-9][0-9]}
     if strstr "$mods_to_load" " $mod "; then
-	dinfo "*** Sourcing module $mod"
-	if [[ $kernel_only = yes ]]; then
-	    [[ -x $moddir/installkernel ]] && . "$moddir/installkernel"
-	else
-	    . "$moddir/install"
-	    if [[ $no_kernel != yes && -x $moddir/installkernel ]]; then
-		. "$moddir/installkernel"
-	    fi
-	fi
-	mods_to_load=${mods_to_load// $mod /}
+        dinfo "*** Sourcing module $mod"
+        if [[ $kernel_only = yes ]]; then
+            [[ -x $moddir/installkernel ]] && . "$moddir/installkernel"
+        else
+            . "$moddir/install"
+            if [[ $no_kernel != yes && -x $moddir/installkernel ]]; then
+                . "$moddir/installkernel"
+            fi
+        fi
+        mods_to_load=${mods_to_load// $mod /}
     fi
 done
 unset moddir
@@ -330,45 +339,38 @@ if [[ $include_src && $include_target ]]; then
 fi
 
 for item in $install_items; do
-   dracut_install "$item"
+    dracut_install "$item"
 done
 unset item
 
 # make sure that library links are correct and up to date
 cp -ar /etc/ld.so.conf* "$initdir"/etc
-ldconfig -r "$initdir" || [[ $UID != "0" ]] && dinfo "ldconfig might need uid=0 (root) for chroot()"
+ldconfig -r "$initdir" || [[ $UID != "0" ]] && \
+    dinfo "ldconfig might need uid=0 (root) for chroot()"
 
 [[ $beverbose = yes ]] && (du -c "$initdir" | sort -n)
 
 # strip binaries 
 if [[ $do_strip = yes ]] ; then
     for p in strip grep find; do 
-	if ! type -P $p >/dev/null; then
-	    derror "Could not find '$p'. You should run $0 with '--nostrip'."
-	    do_strip=no
-	fi
+        if ! type -P $p >/dev/null; then
+            derror "Could not find '$p'. You should run $0 with '--nostrip'."
+            do_strip=no
+        fi
     done
 fi
 
 if [[ $do_strip = yes ]] ; then
-    for f in $(find "$initdir" -type f \( -perm -0100 -or -perm -0010 -or -perm -0001 -or -path '*/lib/modules/*.ko' \) ); do
-	dinfo "Stripping $f"
-	strip -g "$f" 2>/dev/null|| :
-        #
-        # FIXME: only strip -g for now
-        #
-	#strip -g --strip-unneeded "$f" || :
-	#note="-R .note"
-	#if objdump -h $f | grep '^[ 	]*[0-9]*[ 	]*.note[ 	]' -A 1 | \
-	#    grep -q ALLOC; then
-	#    note=
-	#fi
-	#strip -R .comment $note "$f" || :
+    for f in $(find "$initdir" -type f \
+        \( -perm -0100 -or -perm -0010 -or -perm -0001 \
+           -or -path '*/lib/modules/*.ko' \) ); do
+        dinfo "Stripping $f"
+        strip -g "$f" 2>/dev/null|| :
     done
 fi
 
 type hardlink &>/dev/null && {
-	hardlink "$initdir" 2>&1
+    hardlink "$initdir" 2>&1
 }
 
 if ! ( cd "$initdir"; find . |cpio -R 0:0 -H newc -o --quiet | \
diff --git a/dracut-functions b/dracut-functions
--- a/dracut-functions
+++ b/dracut-functions
@@ -1,4 +1,6 @@
 #!/bin/bash
+# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
+# ex: ts=8 sw=4 sts=4 et filetype=sh
 #
 # functions used by dracut and other tools.
 #
@@ -58,8 +60,8 @@ vercmp() {
 # Log initrd creation.
 if ! [[ $dracutlogfile ]]; then
     [[ $dracutbasedir = /usr/share/dracut ]] && \
-	dracutlogfile=/var/log/dracut.log || \
-	dracutlogfile=/tmp/dracut.log
+        dracutlogfile=/var/log/dracut.log || \
+        dracutlogfile=/tmp/dracut.log
 #    [[ -w $dracutlogfile ]] || dracutlogfile=/tmp/dracut.log
     if [[ -w $dracutlogfile ]]; then
         >"$dracutlogfile"
@@ -99,21 +101,21 @@ get_fs_env() {
     [[ $ID_FS_TYPE ]] && return
 
     if [[ -x /lib/udev/vol_id ]]; then
-	eval $(/lib/udev/vol_id --export $1)
+        eval $(/lib/udev/vol_id --export $1)
     elif find_binary blkid >/dev/null; then
-	eval $(blkid -o udev $1)
+        eval $(blkid -o udev $1)
     else
-	return 1
+        return 1
     fi
 }
 
 get_fs_type() (
     [[ $1 ]] || return
     if [[ $1 != ${1#/dev/block/nfs:} ]] \
-	|| [[ $1 != ${1#/dev/block/nfs3:} ]] \
-	|| [[ $1 != ${1#/dev/block/nfs4:} ]]; then
-	echo "nfs"
-	return
+        || [[ $1 != ${1#/dev/block/nfs3:} ]] \
+        || [[ $1 != ${1#/dev/block/nfs4:} ]]; then
+        echo "nfs"
+        return
     fi
     get_fs_env $1 || return
     echo $ID_FS_TYPE
@@ -127,32 +129,32 @@ get_fs_uuid() (
 # finds the major:minor of the block device backing the root filesystem.
 find_block_device() {
     local x mpt majmin dev fs misc maj min
-    if [[ $use_fstab != yes ]]; then	
-	while read x x majmin x mpt x x fs misc; do
+    if [[ $use_fstab != yes ]]; then    
+        while read x x majmin x mpt x x fs misc; do
             [[ $fs = nfs ]] && { echo $dev; return 0;}
             [[ $fs = nfs3 ]] && { echo $dev; return 0;}
             [[ $fs = nfs4 ]] && { echo $dev; return 0;}
-	    if [[ $mpt = $1 ]] && [[ ${majmin#0:} = $majmin ]]; then
-		echo $majmin; 
-		return 0 # we have a winner!
-	    fi
-	done < /proc/self/mountinfo       
+            if [[ $mpt = $1 ]] && [[ ${majmin#0:} = $majmin ]]; then
+                echo $majmin; 
+                return 0 # we have a winner!
+            fi
+        done < /proc/self/mountinfo       
     fi
     # fall back to /etc/fstab    
     while read dev mpt fs misc; do
-	if [[ $mpt = $1 ]]; then
+        if [[ $mpt = $1 ]]; then
             [[ $fs = nfs ]] && { echo $dev; return 0;}
             [[ $fs = nfs3 ]] && { echo $dev; return 0;}
             [[ $fs = nfs4 ]] && { echo $dev; return 0;}
             [[ $dev != ${dev#UUID=} ]] && dev=/dev/disk/by-uuid/${dev#UUID=}
             [[ $dev != ${dev#LABEL=} ]] && dev=/dev/disk/by-label/${dev#LABEL=}
-	    [[ -b $dev ]] || return 1 # oops, not a block device.
-	    ls -nLl "$dev" | { 
-		read x x x x maj min x;
-		maj=${maj//,/}; 
-		echo $maj:$min; 
-	    } && return 0
-	fi
+            [[ -b $dev ]] || return 1 # oops, not a block device.
+            ls -nLl "$dev" | { 
+                read x x x x maj min x;
+                maj=${maj//,/}; 
+                echo $maj:$min; 
+            } && return 0
+        fi
     done < /etc/fstab
     return 1;
 }
@@ -169,12 +171,12 @@ check_block_and_slaves() {
     "$1" $2 && return
     check_vol_slaves "$@" && return 0
     if [[ -f /sys/dev/block/$2/../dev ]]; then
-	check_block_and_slaves $1 $(cat "/sys/dev/block/$2/../dev") &&  return 0
+        check_block_and_slaves $1 $(cat "/sys/dev/block/$2/../dev") &&  return 0
     fi
     [[ -d /sys/dev/block/$2/slaves ]] || return 1
     for x in /sys/dev/block/$2/slaves/*/dev; do
         [[ -f $x ]] || continue
-	check_block_and_slaves $1 $(cat "$x") &&  return 0
+        check_block_and_slaves $1 $(cat "$x") &&  return 0
     done
     return 1
 }
@@ -191,19 +193,19 @@ get_numeric_dev() {
 # And the volume group might be bigger than the devices the LV needs.
 check_vol_slaves() {
     for i in /dev/mapper/*; do 
-	lv=$(get_numeric_dev $i)
-	if [[ $lv = $2 ]]; then
-	    vg=$(lvm lvs --noheadings -o vg_name $i 2>/dev/null)
-	    # strip space
-	    vg=$(echo $vg)
-	    if [[ $vg ]]; then
-		for pv in $(lvm vgs --noheadings -o pv_name "$vg" 2>/dev/null); \
-		    do
- 		    check_block_and_slaves $1 $(get_numeric_dev $pv) \
-			&&  return 0
-		done
-	    fi
-	fi
+        lv=$(get_numeric_dev $i)
+        if [[ $lv = $2 ]]; then
+            vg=$(lvm lvs --noheadings -o vg_name $i 2>/dev/null)
+            # strip space
+            vg=$(echo $vg)
+            if [[ $vg ]]; then
+                for pv in $(lvm vgs --noheadings -o pv_name "$vg" 2>/dev/null); \
+                    do
+                    check_block_and_slaves $1 $(get_numeric_dev $pv) \
+                        &&  return 0
+                done
+            fi
+        fi
     done
     return 1
 }
@@ -286,13 +288,13 @@ inst_library() {
     local src=$1 dest=${2:-$1} lib reallib symlink
     [[ -e $initdir$dest ]] && return 0
     if [[ -L $src ]]; then
-	reallib=$(readlink -f "$src")
-	lib=${src##*/}
-	inst_simple "$reallib" "$reallib"
-	inst_dir "${dest%/*}"
-	(cd "${initdir}${dest%/*}" && ln -s "$reallib" "$lib")
+        reallib=$(readlink -f "$src")
+        lib=${src##*/}
+        inst_simple "$reallib" "$reallib"
+        inst_dir "${dest%/*}"
+        (cd "${initdir}${dest%/*}" && ln -s "$reallib" "$lib")
     else
-	inst_simple "$src" "$dest"
+        inst_simple "$src" "$dest"
     fi
 
     # Create additional symlinks.  See rev_symlinks description.
@@ -310,7 +312,7 @@ find_binary() {
     local binpath="/bin /sbin /usr/bin /usr/sbin" p
     [[ -z ${1##/*} && -x $1 ]] && { echo $1; return 0; } 
     for p in $binpath; do
-	[[ -x $p/$1 ]] && { echo "$p/$1"; return 0; }
+        [[ -x $p/$1 ]] && { echo "$p/$1"; return 0; }
     done
     return 1
 }
@@ -326,33 +328,33 @@ inst_binary() {
     [[ -e $initdir$target ]] && return 0
     # I love bash!
     LC_ALL=C ldd $bin 2>/dev/null | while read line; do
-	[[ $line = 'not a dynamic executable' ]] && return 1
-	if [[ $line =~ not\ found ]]; then
-	    derror "Missing a shared library required by $bin."
-	    derror "Run \"ldd $bin\" to find out what it is."
-	    derror "dracut cannot create an initrd."
-	    exit 1
-	fi
-	so_regex='([^ ]*/lib[^/]*/[^ ]*\.so[^ ]*)'
-	[[ $line =~ $so_regex ]] || continue
-	FILE=${BASH_REMATCH[1]}
-	[[ -e ${initdir}$FILE ]] && continue
-	# see if we are loading an optimized version of a shared lib.
-	lib_regex='^(/lib[^/]*).*'
-	if [[ $FILE =~ $lib_regex ]]; then
+        [[ $line = 'not a dynamic executable' ]] && return 1
+        if [[ $line =~ not\ found ]]; then
+            derror "Missing a shared library required by $bin."
+            derror "Run \"ldd $bin\" to find out what it is."
+            derror "dracut cannot create an initrd."
+            exit 1
+        fi
+        so_regex='([^ ]*/lib[^/]*/[^ ]*\.so[^ ]*)'
+        [[ $line =~ $so_regex ]] || continue
+        FILE=${BASH_REMATCH[1]}
+        [[ -e ${initdir}$FILE ]] && continue
+        # see if we are loading an optimized version of a shared lib.
+        lib_regex='^(/lib[^/]*).*'
+        if [[ $FILE =~ $lib_regex ]]; then
             TLIBDIR=${BASH_REMATCH[1]}
             BASE=${FILE##*/}
-	    # prefer nosegneg libs, then unoptimized ones.
-	    for f in "$TLIBDIR/i686/nosegneg" "$TLIBDIR"; do
-		[[ -e $f/$BASE ]] || continue
-		FILE=$f/$BASE
-		break
-	    done
-	    inst_library "$FILE" "$TLIBDIR/$BASE"
+            # prefer nosegneg libs, then unoptimized ones.
+            for f in "$TLIBDIR/i686/nosegneg" "$TLIBDIR"; do
+                [[ -e $f/$BASE ]] || continue
+                FILE=$f/$BASE
+                break
+            done
+            inst_library "$FILE" "$TLIBDIR/$BASE"
             IF_dynamic=yes
-	    continue
-	fi
-        inst_library "$FILE" 
+            continue
+            fi
+            inst_library "$FILE" 
     done
     inst_simple "$bin" "$target"
 }
@@ -384,7 +386,7 @@ inst_symlink() {
 find_rule() {
     [[ -f $1 ]] && { echo "$1"; return 0; }
     for r in . /lib/udev/rules.d /etc/udev/rules.d $dracutbasedir/rules.d; do
-	[[ -f $r/$1 ]] && { echo "$r/$1"; return 0; }
+        [[ -f $r/$1 ]] && { echo "$r/$1"; return 0; }
     done
     return 1
 }
@@ -409,14 +411,14 @@ inst() {
     case $# in
         1) ;;
         2) [[ ! $initdir && -d $2 ]] && export initdir=$2
-           [[ $initdir = $2 ]] && set $1;;
+            [[ $initdir = $2 ]] && set $1;;
         3) [[ -z $initdir ]] && export initdir=$2 
-           set $1 $3;;
+            set $1 $3;;
         *) derror "inst only takes 1 or 2 or 3 arguments"
-           exit 1;;
+            exit 1;;
     esac
     for x in inst_symlink inst_script inst_binary inst_simple; do
-       $x "$@" && return 0
+        $x "$@" && return 0
     done
     return 1
 }
@@ -426,31 +428,31 @@ inst() {
 # All hooks should be POSIX/SuS compliant, they will be sourced by init.
 inst_hook() {
     if ! [[ -f $3 ]]; then
-	derror "Cannot install a hook ($3) that does not exist."
-	derror "Aborting initrd creation."
-	exit 1
+        derror "Cannot install a hook ($3) that does not exist."
+        derror "Aborting initrd creation."
+        exit 1
     elif ! strstr "$hookdirs" "$1"; then
-	derror "No such hook type $1. Aborting initrd creation." 
-	exit 1
+        derror "No such hook type $1. Aborting initrd creation." 
+        exit 1
     fi
     inst_simple "$3" "/${1}/${2}${3##*/}"
 }
 
 dracut_install() {
     if [[ $1 = '-o' ]]; then 
-	local optional=yes
-	shift
+        local optional=yes
+        shift
     fi
     while (($# > 0)); do
-	if ! inst "$1" ; then
-	    if [[ $optional = yes ]]; then
-		dwarning "Skipping program $1 as it cannot be found and is flagged to be optional"
-	    else
-		derror "Failed to install $1"
-		exit 1
+        if ! inst "$1" ; then
+            if [[ $optional = yes ]]; then
+                dwarning "Skipping program $1 as it cannot be found and is flagged to be optional"
+            else
+                derror "Failed to install $1"
+                exit 1
             fi
-	fi
-	shift
+        fi
+        shift
     done
 }
 
@@ -511,15 +513,15 @@ check_module_deps() {
     [[ -d $moddir && -x $moddir/install ]] || return 1
     # if we do not have a check script, we are unconditionally included
     if [[ -x $moddir/check ]]; then
-	"$moddir/check"
+        "$moddir/check"
         ret=$?
-	# a return value of 255 = load module only as a dependency.
-	((ret==0||ret==255)) || return 1
-	for dep in $("$moddir/check" -d); do
-	    check_module_deps "$dep" && continue
-	    dwarning "Dependency $mod failed."
-	    return 1
-	done
+        # a return value of 255 = load module only as a dependency.
+        ((ret==0||ret==255)) || return 1
+        for dep in $("$moddir/check" -d); do
+            check_module_deps "$dep" && continue
+            dwarning "Dependency $mod failed."
+            return 1
+        done
     fi
     mods_to_load+=" $1 "
 }
@@ -535,9 +537,9 @@ should_source_module() {
     [[ -x $1/check ]] || return 0
     "$1/check" $hostonly || continue
     for dep in $("$1/check" -d); do
-	check_module_deps "$dep" && continue
-	dwarning "Cannot load dracut module \"$mod\", dependencies failed."
-	return 1
+        check_module_deps "$dep" && continue
+        dwarning "Cannot load dracut module \"$mod\", dependencies failed."
+        return 1
     done
 }
 
@@ -545,33 +547,33 @@ check_modules() {
     local modcheck;
     local mod;
     for moddir in "$dracutbasedir/modules.d"/[0-9][0-9]*; do
-	local mod=${moddir##*/}; mod=${mod#[0-9][0-9]}
-	# If we are already scheduled to be loaded, no need to check again.
-	strstr " $mods_to_load " " $mod " && continue
-	# This should never happen, but...
-	[[ -d $moddir ]] || continue
+        local mod=${moddir##*/}; mod=${mod#[0-9][0-9]}
+        # If we are already scheduled to be loaded, no need to check again.
+        strstr " $mods_to_load " " $mod " && continue
+        # This should never happen, but...
+        [[ -d $moddir ]] || continue
         strstr " $omit_dracutmodules " " $mod " && continue
 
         if ! strstr " $dracutmodules $add_dracutmodules " " $mod "; then
             # module not in our list
-	    if [[ $dracutmodules = all ]]; then
+            if [[ $dracutmodules = all ]]; then
                 # check, if we can install this module
-	        should_source_module "$moddir" || continue
+                should_source_module "$moddir" || continue
             else
                 # skip this module
                 continue
             fi
-	else
-	    if [ -x "$moddir/check" ] \
+        else
+            if [ -x "$moddir/check" ] \
                 && "$moddir/check" -d > /dev/null 2>&1; then
-		check_module_deps "$mod" || {
-		    dwarning "Cannot load dracut module \"$mod\", dependencies failed."
+                check_module_deps "$mod" || {
+                    dwarning "Cannot load dracut module \"$mod\", dependencies failed."
                     continue
                 }
             fi
         fi
 
-	mods_to_load+=" $mod "
+        mods_to_load+=" $mod "
     done
 
     modcheck=$add_dracutmodules
@@ -589,18 +591,18 @@ install_kmod_with_fw() {
     local modname=${1##*/} fwdir found
     modname=${modname%.ko*}
     inst_simple "$1" "/lib/modules/$kernel/${1##*/lib/modules/$kernel/}" || \
-	return 0 # no need to go further if the module is already installed
+        return 0 # no need to go further if the module is already installed
     for fw in $(modinfo -k $kernel -F firmware $1 2>/dev/null); do
-	found=''
-	for fwdir in $fw_dir; do
-	    if [[ -d $fwdir && -f $fwdir/$fw ]]; then
-		inst_simple "$fwdir/$fw" "/lib/firmware/$fw"
-		found=yes
-	    fi
-	done
-	if [[ $found != yes ]]; then
-	    dinfo "Possible missing firmware \"${fw}\" for kernel module \"${mod}.ko\""
-	fi
+        found=''
+        for fwdir in $fw_dir; do
+            if [[ -d $fwdir && -f $fwdir/$fw ]]; then
+                inst_simple "$fwdir/$fw" "/lib/firmware/$fw"
+                found=yes
+            fi
+        done
+        if [[ $found != yes ]]; then
+            dinfo "Possible missing firmware \"${fw}\" for kernel module \"${mod}.ko\""
+        fi
     done
 }
 
@@ -614,9 +616,9 @@ for_each_kmod_dep() {
     local func=$1 kmod=$2 cmd modpapth options
     shift 2
     modprobe "$@" --ignore-install --show-depends $kmod 2>/dev/null | \
-	while read cmd modpath options; do
-	    [[ $cmd = insmod ]] || continue
-	    $func $modpath
+        while read cmd modpath options; do
+        [[ $cmd = insmod ]] || continue
+        $func $modpath
     done
 }
 
@@ -630,16 +632,16 @@ for_each_kmod_dep() {
 # This function returns the full filenames of modules that match $1
 filter_kernel_modules () (
     if ! [[ $hostonly ]]; then
-	filtercmd='find "$srcmods/kernel/drivers" -name "*.ko" -o -name "*.ko.gz"'
+        filtercmd='find "$srcmods/kernel/drivers" -name "*.ko" -o -name "*.ko.gz"'
     else
-	filtercmd='cut -d " " -f 1 </proc/modules|xargs modinfo -F filename -k $kernel'
+        filtercmd='cut -d " " -f 1 </proc/modules|xargs modinfo -F filename -k $kernel'
     fi
     for modname in $(eval $filtercmd); do
         case $modname in
             *.ko) "$1" "$modname" && echo "$modname";;
             *.ko.gz) gzip -dc "$modname" > $initdir/$$.ko
-                     $1 $initdir/$$.ko && echo "$modname"
-                     rm -f $initdir/$$.ko;;
+                $1 $initdir/$$.ko && echo "$modname"
+                rm -f $initdir/$$.ko;;
         esac
     done
 )
@@ -649,46 +651,46 @@ instmods() {
     [[ $no_kernel = yes ]] && return
     local mod mpargs modpath modname cmd moddirname
     while (($# > 0)); do
-	mod=${1%.ko*}
-	case $mod in
-	    =*) # This introduces 2 incompatible meanings for =* arguments
+        mod=${1%.ko*}
+        case $mod in
+            =*) 
+                # This introduces 2 incompatible meanings for =* arguments
                 # to instmods.  We need to decide which one to keep.
-		if [[ $mod = =ata && -f $srcmods/modules.block ]] ; then 
-		    instmods $mpargs $(egrep 'ata|ahci' "${srcmods}/modules.block")
-		elif [ -f $srcmods/modules.${mod#=} ]; then
-		    instmods $mpargs $(cat ${srcmods}/modules.${mod#=} )
-		else
-		    instmods $mpargs $(find "$srcmods" -path "*/${mod#=}/*")
-		fi
-		;;
-	    --*) mod=${mod##*/}
-                 mpargs+=" $mod";;
+                if [[ $mod = =ata && -f $srcmods/modules.block ]] ; then 
+                    instmods $mpargs $(egrep 'ata|ahci' "${srcmods}/modules.block")
+                elif [ -f $srcmods/modules.${mod#=} ]; then
+                    instmods $mpargs $(cat ${srcmods}/modules.${mod#=} )
+                else
+                    instmods $mpargs $(find "$srcmods" -path "*/${mod#=}/*")
+                fi
+                ;;
+            --*) 
+                mod=${mod##*/}
+                mpargs+=" $mod";;
             i2o_scsi) shift; continue;; # Do not load this diagnostic-only module
-	    *)  mod=${mod##*/}
+            *)  mod=${mod##*/}
                 # if we are already installed, skip this module and go on
-	        # to the next one.
-	        [[ -f $initdir/$1 ]] && { shift; continue; }
-		# If we are building a host-specific initramfs and this
-		# module is not already loaded, move on to the next one.
-		[[ $hostonly ]] && ! grep -qe "\<${mod//-/_}\>" /proc/modules && \
-	        ! echo $add_drivers | grep -qe "\<${mod}\>" &&	{
-		    shift; continue; 
-		}
+                # to the next one.
+                [[ -f $initdir/$1 ]] && { shift; continue; }
+                # If we are building a host-specific initramfs and this
+                # module is not already loaded, move on to the next one.
+                [[ $hostonly ]] && ! grep -qe "\<${mod//-/_}\>" /proc/modules && \
+                    ! echo $add_drivers | grep -qe "\<${mod}\>" &&  {
+                    shift; continue; 
+                }
 
-		# We use '-d' option in modprobe only if modules prefix path
-		# differs from default '/'.  This allows us to use Dracut with
-		# old version of modprobe which doesn't have '-d' option.
-		moddirname=${srcmods%%/lib/modules/*}
-		[[ -n ${moddirname} ]] && moddirname="-d ${moddirname}/"
+                # We use '-d' option in modprobe only if modules prefix path
+                # differs from default '/'.  This allows us to use Dracut with
+                # old version of modprobe which doesn't have '-d' option.
+                moddirname=${srcmods%%/lib/modules/*}
+                [[ -n ${moddirname} ]] && moddirname="-d ${moddirname}/"
 
-		# ok, load the module, all its dependencies, and any firmware
-		# it may require
-		for_each_kmod_dep install_kmod_with_fw $mod \
-		    --set-version $kernel ${moddirname}
-		;;
-	esac      
-	shift
+                # ok, load the module, all its dependencies, and any firmware
+                # it may require
+                for_each_kmod_dep install_kmod_with_fw $mod \
+                    --set-version $kernel ${moddirname}
+                ;;
+    esac      
+    shift
     done
 } 
-
-# vim:ts=8:sw=4:sts=4:et
diff --git a/modules.d/40network/ifup b/modules.d/40network/ifup
--- a/modules.d/40network/ifup
+++ b/modules.d/40network/ifup
@@ -1,4 +1,6 @@
 #!/bin/sh
+# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
+# ex: ts=8 sw=4 sts=4 et filetype=sh
 #
 # We don't need to check for ip= errors here, that is handled by the
 # cmdline parser script
@@ -14,16 +16,16 @@ do_dhcp() {
     # XXX add -V vendor class and option parsing per kernel
     echo "Starting dhcp for interface $netif"
     dhclient "$@" -1 -q -cf /etc/dhclient.conf -pf /tmp/dhclient.$netif.pid -lf /tmp/dhclient.$netif.lease $netif \
-    || echo "dhcp failed"
+        || echo "dhcp failed"
 }
 
 load_ipv6() {
     modprobe ipv6
     i=0
     while [ ! -d /proc/sys/net/ipv6 ]; do
-	i=$(($i+1))
-	[ $i -gt 10 ] && break
-	sleep 0.1
+        i=$(($i+1))
+        [ $i -gt 10 ] && break
+        sleep 0.1
     done
 }
 
@@ -33,17 +35,17 @@ do_ipv6auto() {
         echo 0 > /proc/sys/net/ipv6/conf/$netif/forwarding 
         echo 1 > /proc/sys/net/ipv6/conf/$netif/accept_ra
         echo 1 > /proc/sys/net/ipv6/conf/$netif/accept_redirects
-	echo ip link set $netif up 
-	echo wait_for_if_up $netif
+        echo ip link set $netif up 
+        echo wait_for_if_up $netif
     } > /tmp/net.$netif.up
 
     [ -n "$hostname" ] && echo "echo $hostname > /proc/sys/kernel/hostname" > /tmp/net.$netif.hostname
 
     namesrv=$(getargs nameserver)
     if  [ -n "$namesrv" ] ; then
-	for s in $namesrv; do
-	    echo nameserver $s 
-	done
+        for s in $namesrv; do
+            echo nameserver $s 
+        done
     fi >> /tmp/net.$netif.resolv.conf
 
 
@@ -56,12 +58,12 @@ do_static() {
     strstr $ip '*:*:*' && load_ipv6
 
     {
-	echo ip link set $netif up 
-	echo wait_for_if_up $netif
-	# do not flush addr for ipv6
-	strstr $ip '*:*:*' || \
-	    echo ip addr flush dev $netif
-	echo ip addr add $ip/$mask dev $netif
+        echo ip link set $netif up 
+        echo wait_for_if_up $netif
+        # do not flush addr for ipv6
+        strstr $ip '*:*:*' || \
+            echo ip addr flush dev $netif
+        echo ip addr add $ip/$mask dev $netif
     } > /tmp/net.$netif.up
 
     [ -n "$gw" ] && echo ip route add default via $gw dev $netif > /tmp/net.$netif.gw
@@ -69,9 +71,9 @@ do_static() {
 
     namesrv=$(getargs nameserver)
     if  [ -n "$namesrv" ] ; then
-	for s in $namesrv; do
-	    echo nameserver $s 
-	done
+        for s in $namesrv; do
+            echo nameserver $s 
+        done
     fi >> /tmp/net.$netif.resolv.conf
 
     echo online > /sys/class/net/$netif/uevent
@@ -130,9 +132,9 @@ ip=$(getarg ip)
 
 if [ -z "$ip" ]; then
     if [ "$netroot" = "dhcp6" ]; then
-	do_dhcp -6
+        do_dhcp -6
     else
-	do_dhcp -4
+        do_dhcp -4
     fi
 fi
 
@@ -140,24 +142,24 @@ fi
 # looking for ip= lines
 for p in $(getargs ip=); do
     ip_to_var $p
-	
+    
     # If this option isn't directed at our interface, skip it
     [ -n "$dev" ] && [ "$dev" != "$netif" ] && continue
 
     # Store config for later use
     for i in ip srv gw mask hostname; do
-	eval '[ "$'$i'" ] && echo '$i'="$'$i'"'
+        eval '[ "$'$i'" ] && echo '$i'="$'$i'"'
     done > /tmp/net.$netif.override
 
     case $autoconf in
-	dhcp|on|any)
-	    do_dhcp -4 ;;
-	dhcp6)
-	    do_dhcp -6 ;;
-	auto6)
-	    do_ipv6auto ;;
+        dhcp|on|any)
+            do_dhcp -4 ;;
+        dhcp6)
+            do_dhcp -6 ;;
+        auto6)
+            do_ipv6auto ;;
         *) 
-	    do_static ;;
+            do_static ;;
     esac
     break
 done
diff --git a/modules.d/90dmsquash-live/dmsquash-live-root b/modules.d/90dmsquash-live/dmsquash-live-root
--- a/modules.d/90dmsquash-live/dmsquash-live-root
+++ b/modules.d/90dmsquash-live/dmsquash-live-root
@@ -1,4 +1,6 @@
 #!/bin/sh
+# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
+# ex: ts=8 sw=4 sts=4 et filetype=sh
 
 . /lib/dracut-lib.sh
 [ -f /tmp/root.info ] && . /tmp/root.info
@@ -32,8 +34,8 @@ getarg check || check=""
 if [ -n "$check" ]; then
     checkisomd5 --verbose $livedev || :
     if [ $? -ne 0 ]; then
-	die "CD check failed!"
-	exit 1
+        die "CD check failed!"
+        exit 1
     fi
 fi
 
@@ -79,7 +81,7 @@ do_live_overlay() {
         if [ -f /overlayfs$pathspec -a -w /overlayfs$pathspec ]; then
             losetup $OVERLAY_LOOPDEV /overlayfs$pathspec
             if [ -n "$reset_overlay" ]; then
-               dd if=/dev/zero of=$OVERLAY_LOOPDEV bs=64k count=1 2>/dev/null
+                dd if=/dev/zero of=$OVERLAY_LOOPDEV bs=64k count=1 2>/dev/null
             fi
             setup="yes"
         fi
@@ -88,8 +90,8 @@ do_live_overlay() {
 
     if [ -z "$setup" ]; then
         if [ -n "$devspec" -a -n "$pathspec" ]; then
-           warn "Unable to find persistent overlay; using temporary"
-           sleep 5
+            warn "Unable to find persistent overlay; using temporary"
+            sleep 5
         fi
 
         dd if=/dev/null of=/overlay bs=1024 count=1 seek=$((512*1024)) 2> /dev/null
@@ -124,7 +126,7 @@ fi
 
 # we might have just an embedded ext3 to use as rootfs (uncompressed live)
 if [ -e /dev/.initramfs/live/${live_dir}/ext3fs.img ]; then
-  EXT3FS="/dev/.initramfs/live/${live_dir}/ext3fs.img"
+    EXT3FS="/dev/.initramfs/live/${live_dir}/ext3fs.img"
 fi
 
 if [ -n "$EXT3FS" ] ; then
@@ -136,7 +138,7 @@ fi
 
 # we might have an embedded ext3 on squashfs to use as rootfs (compressed live)
 if [ -e /dev/.initramfs/live/${live_dir}/squashfs.img ]; then
-  SQUASHED="/dev/.initramfs/live/${live_dir}/squashfs.img"
+    SQUASHED="/dev/.initramfs/live/${live_dir}/squashfs.img"
 fi
 
 if [ -e "$SQUASHED" ] ; then
