Support checking the iso
Support checking the iso image with checkisomd5 if available

diff --git a/modules.d/90dmsquash-live/dmsquash-live-root b/modules.d/90dmsquash-live/dmsquash-live-root
--- a/modules.d/90dmsquash-live/dmsquash-live-root
+++ b/modules.d/90dmsquash-live/dmsquash-live-root
@@ -14,7 +14,19 @@ fi
 [ -z "$1" ] && exit 1
 livedev="$1"
 
-# FIXME: do cd check here
+# FIXME: we need to be able to hide the plymouth splash for the check really
+[ -e $livedev ] & fs=$(blkid -s TYPE -o value $livedev)
+if [ "$fs" == "iso9660" -o "$fs" = "udf" ]; then
+    check="yes"
+fi
+getarg check || check=""
+if [ -n "$check" ]; then
+    checkisomd5 --verbose $livedev || :
+    if [ $? -ne 0 ]; then
+	echo "CD check failed!"
+	exit 1
+    fi
+fi
 
 getarg ro && liverw=ro
 getarg rw && liverw=rw
@@ -32,7 +44,6 @@ overlay=off
 live_dir="LiveOS"
 live_ram=0
 reset_overlay=0
-check=0
 
 # overlay setup helper function
 do_live_overlay() {
