Add support for in-initramfs live images with "root=live:/path/name.img"
This allows creation of initramfs images which contain a Live system.
The primary use for this is keeping very large initramfs-based systems
(e.g. anaconda, the Fedora installer) compressed in-memory, by using a
compressed filesystem image like squashfs or btrfs.

dmsquash-live-genrules.sh will initqueue dmsquash-live-root itself
(rather than making udev rules) if the given live "device" is actually
an existing, plain file.

parse-dmsquash-live.sh will only accept paths that end in ".img".
dmsquash-live-root will only handle images named "*squashfs.img",
"*ext3fs.img", or "*btrfs.img".

diff --git a/modules.d/90dmsquash-live/dmsquash-live-root b/modules.d/90dmsquash-live/dmsquash-live-root
--- a/modules.d/90dmsquash-live/dmsquash-live-root
+++ b/modules.d/90dmsquash-live/dmsquash-live-root
@@ -44,11 +44,19 @@ getarg rw && liverw=rw
 [ -z "$liverw" ] && liverw=ro
 # mount the backing of the live image first
 mkdir -p /dev/.initramfs/live
-mount -n -t $fstype -o $liverw $livedev /dev/.initramfs/live
-RES=$?
-if [ "$RES" != "0" ]; then
-    die "Failed to mount block device of live image"
-    exit 1
+if [ -f $livedev ]; then
+    # no mount needed - we've already got the LiveOS image in initramfs
+    case $livedev in
+        *squashfs.img) SQUASHED=$livedev ;;
+        *ext3fs.img|*btrfs.img) FSIMG=$livedev ;;
+    esac
+else
+    mount -n -t $fstype -o $liverw $livedev /dev/.initramfs/live
+    RES=$?
+    if [ "$RES" != "0" ]; then
+        die "Failed to mount block device of live image"
+        exit 1
+    fi
 fi
 
 # overlay setup helper function
